---
##
# pcd-systems/common prepare
#
  
- name: add authorized key for root user
  authorized_key: 
    user=root
    key="{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"
    

# @todo, make this optional?
- name: set root user ssh identify
  copy:
    dest=root/.ssh/{{ item.0 }}
    mode=0600
    src={{ item.1 }}
    owner=root
    group=root
  with_together:
    - [ 'id_rsa', 'id_rsa.pub' ]
    - [ '{{ ansible_ssh_private_key_file }}', '{{ ansible_ssh_private_key_file }}.pub' ]
    
  
- name: allow ssh PubkeyAuthentication
  lineinfile: 
    dest={{ os_sshd_config_file }}
    regexp="^PubkeyAuthentication"
    line="PubkeyAuthentication yes"
    state=present
  notify: 
    - sshd restart

# ensure user common groups "nogroup" exists as a system group
- name: add common groups
  group: name={{ item }} system=yes state=present
  with_items:
    - nogroup
    - ansible
  
  
# Ensure /etc/ansible metadirs 
##############################

- name: ensure ansible-pcd metadirs
  file: 
    path={{ item }}
    state=directory
    owner=root
    group=ansible
    mode=0755
  with_items:
    - /etc/ansible
    - /etc/ansible/conf.d